### ISSUE TITLE
[PyLavController] controller channel improvement

### ISSUE THREAD

**Issue by ocformula** [Drapersniper/PyLav-Cogs#324]
**Is your feature request related to a problem? Please describe.**

It needs the ability to automatically clean the controller channel.
Also, if user uses a bot command with a prefix on the controller channel, that message will not be deleted.

**Describe the solution you'd like**

It needs the ability to automatically clean the controller channel.

**Describe alternatives you've considered**

**Additional context**

**Comment by Drapersniper** [comment]
Currently the listener used is "on message that does not start with prefix" - I'm skeptical about changing this listener to "any message". 

I'm of the mindset you should be restricting users from using any commands in the controller channel if you don't want them using commands in there and it should not be up to the cog to do additional work just in the of chance some users may want it.

**Comment by Drapersniper** [comment]
Can you clarify whether your issue is just in regards to being able to use other commands in the channel or if it's something else please.

**Comment by ocformula** [comment]
It's in regards to being able to use other commands in the channel.
In channels with PyLavController set up, some people use non-slash commands including play and skip.
In this case, both the messages in which those commands are used and the response messages returned by Red Bot are left in the chat, and I have to clean them up manually.

**Comment by Drapersniper** [comment]
I need to think on this - I wanna avoid doing a "on any new message process it to see if its valid" since it can be very spammy on larger bots and have significant performance impacts on the bot

**Comment by Drapersniper** [comment]
I will be adding a configurable option that allows you to listen to all messages, which will be off by default.

**Comment by Drapersniper** [comment]
Added as part of https://github.com/PyLav/Red-Cogs/commit/8417a2fbeb4920157699fc3fa02df6c7a5f11c04
