### ISSUE TITLE
Something wrong

### ISSUE THREAD

**Issue by wibe01204** [Drapersniper/PyLav-Cogs#327]
`ERROR    [red.downloader] Something went wrong when installing the following requirements: Py-Lav[all]>=1.12.1<1.13`
![image](https://github.com/PyLav/Red-Cogs/assets/90883053/01df37f6-ab10-4b22-8da5-e388ad057fa6)

**Comment by Drapersniper** [comment]
Not enough information to troubleshoot anything here. Please open a new issue with the exact re-production steps and your environment and installation method; as much info as you'd think is enough to look into the issue (Red version, tracebacks, did you change anything in the environment recently, did it work before) and a clear name to what is happening.
