### ISSUE TITLE
What about the 'save' command?

### ISSUE THREAD

**Issue by ocformula** [Drapersniper/PyLav-Cogs#346]
When I listen to songs, sometimes I want to save it.
The difference with the 'np' command is that the 'save' command DMs the result to the user who used the command.
The result shows a brief information about the currently playing song.
In the code below, we only need to modify the get_currently_playing_message function.

    @commands.hybrid_command(
        name="save",
        description=shorten_string(
            max_length=100, string=("DM the song you're currently playing.")
        ),
        extras={"red_force_enable": True},
    )
    @commands.guild_only()
    @requires_player()
    async def command_save(self, context: PyLavContext):
        """Shows which track is currently being played on this server."""
        if isinstance(context, discord.Interaction):
            context = await self.bot.get_context(context)
        if context.interaction and not context.interaction.response.is_done():
            await context.defer(ephemeral=True)
        if not context.player or not context.player.current:
            await context.send(
                embed=await context.pylav.construct_embed(
                    description=("Play music first!"), messageable=context
                ),
                ephemeral=True,
            )
            return
        kwargs = await context.player.get_currently_playing_message(messageable=context)
        await context.send(
            embed=await context.pylav.construct_embed(
                description=("Please check DM.\nIf you don't receive DMs, please enable direct messages from server members."), messageable=context
            ),
            ephemeral=True,
        )
        await context.author.send(**kwargs)

**Comment by Drapersniper** [comment]
I can get behind this as long as a hybrid command is not a requirement (i.e a slash command)

**Comment by Drapersniper** [comment]
An alternative resolution here is an option arg to np that directs the message to your dms

**Comment by Drapersniper** [comment]
Added in https://github.com/PyLav/Red-Cogs/commit/85a27ec3b8b67fbd806944bdd273187a272f4de7
